export enum MovieGenre {
    ACTION = 'Action',
    COMEDY = 'Comedy',
    DRAMA = 'Drama',
    HORROR = 'Horror',
    SCI_FI = 'Sci-Fi',
    ROMANCE = 'Romance',
    THRILLER = 'Thriller',
    ANIMATION = 'Animation',
    DOCUMENTARY = 'Documentary',
    CRIME = 'Crime',
    FANTASY = 'Fantasy',
    ADVENTURE = 'Adventure',
    MUSICAL = 'Musical',
    WESTERN = 'Western',
    MYSTERY = 'Mystery',
    FAMILY = 'Family',
    WAR = 'War',
    HISTORY = 'History',
    MUSIC = 'Music',
    SPORT = 'Sport',
    BIOGRAPHY = 'Biography',
    SHORT = 'Short',
    FILM_NOIR = 'Film-Noir',
    NEWS = 'News',
    REALITY_TV = 'Reality-TV',
    GAME_SHOW = 'Game-Show',
    TALK_SHOW = 'Talk-Show',
    SPORT_EVENT = 'Sport Event',
    PORN = 'Porn',
}

export enum MovieRating {
    G = 'G',
    PG = 'PG',
    PG_13 = 'PG_13',
    R = 'R',
    NC_17 = 'NC_17',
    UNRATED = 'Unrated',
}

export enum MovieStatus {
    RELEASED = 'RELEASED',
    IN_PRODUCTION = 'IN PRODUCTION',
    ANNOUNCED = 'ANNOUNCED',
    CANCELED = 'CANCELED',
    POST_PRODUCTION = 'POST PRODUCTION',
}

export enum Languages{
    ENGLISH = 'ENGLISH',
    HINDI = 'HINDI',
    TAMIL = 'TAMIL',
    TELUGU = 'TELUGU',
    MALAYALAM = 'MALAYALAM',
    KANNADA = 'KANNADA',
    FRENCH = 'FRENCH',
    SPANISH = 'SPANISH',
    GERMAN = 'GERMAN',
    CHINESE = 'CHINESE',
    JAPANESE = 'JAPANESE',
    KOREAN = 'KOREAN',
    ARABIC = 'ARABIC',
    HEBREW = 'HEBREW',
    NIGERIAN = 'NIGERIAN',
    PORTUGUESE = 'PORTUGUESE',
    BURUNDIAN = 'BURUNDIAN',
    SWAHILI = 'SWAHILI',
}