name: Frontend CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'moviebox-frontend/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'moviebox-frontend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: moviebox-frontend/package-lock.json
    
    - name: Install dependencies
      working-directory: ./moviebox-frontend
      run: npm ci
    
    - name: Lint
      working-directory: ./moviebox-frontend
      run: npm run lint
    
    - name: Type check
      working-directory: ./moviebox-frontend
      run: npm run check
    
    - name: Build
      working-directory: ./moviebox-frontend
      run: npm run build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: frontend-build
        path: moviebox-frontend/dist

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: frontend-build
        path: dist
    
    - name: Deploy to production
      run: |
        echo "Deploy frontend to production"
        # Add deployment commands (Netlify, Vercel, S3, etc.)
